-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS certificate.certificates
(
    cert_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 100 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cert_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    completed_date date,
    course_length time without time zone,
    study_time time without time zone,
    skill_id integer,
    platform_id integer,
    issuing_org_id integer,
    showcase boolean,
    cert_code character varying(255) COLLATE pg_catalog."default",
    cloud_path character varying(255) COLLATE pg_catalog."default",
    exam_score integer,
    hands_on boolean,
    repo character varying(255) COLLATE pg_catalog."default",
    posted_linkedin timestamp without time zone,
    tutor_id integer,
    note character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT certificates_pkey PRIMARY KEY (cert_id)
);

CREATE TABLE IF NOT EXISTS certificate.skill_lines
(
    skill_line_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cert_id integer,
    skill_id integer,
    CONSTRAINT skill_lines_pkey PRIMARY KEY (skill_line_id)
);

CREATE TABLE IF NOT EXISTS certificate.skills
(
    skill_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    skill_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    skill_description character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT skills_pkey PRIMARY KEY (skill_id)
);

ALTER TABLE IF EXISTS certificate.skill_lines
    ADD FOREIGN KEY (cert_id)
    REFERENCES certificate.certificates (cert_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS certificate.skill_lines
    ADD FOREIGN KEY (skill_id)
    REFERENCES certificate.skills (skill_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;